### ISSUE TITLE
User-based Rate Limiting?

### ISSUE THREAD

**Issue by Manas73** [long2ice/fastapi-limiter#13]
How do I enable different rates for each user? I know I can have a rate-limit for each user eg: 5 requests per 10 seconds. However, if I want each user to have their own rate limit eg:

- user-1: 5 requests per 10 seconds.
- user-2: 10 requests per 10 seconds.

How do I do achieve different rate limits per user/ip?

**Comment by Manas73** [comment]
I just edited the default Lua Script (will have to store each user's custom limit into Redis and access that as `limit`).

**Comment by long2ice** [comment]
That's a way

**Comment by arthurio** [comment]
@Manas73 That seems like a good option and was thinking about using a similar approach, would you be able to share your solution by any chance?
Also @long2ice , I couldn't find anywhere the reasoning behind using a LUA script to access redis vs. just using python? Is it a performance concern since it seats in the frontline? Did you do any benchmarking?
Thank you both for your time!
